### BASELINE EXPERIMENTATION
This notebook explores training of the model without any hyperparameter tuning
Logistic Regression is going to be used since it is a binary classification
Random Forest Classifier is going to be used also
For the remaining classifiers we use Lazy Predict to train multiple classifiers at a time and ranks them based on their accuracy
we going to use mlflow for tracking the experimentation 
Since there is a class imbalnace we use apply an oversampling technique on the minority class

In [37]:
#import dependencies
import pandas as pd
import numpy as np
import mlflow
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [38]:
#reading the data
data = pd.read_csv(r'C:\Users\IKE\Desktop\Human_VS_AI\eda&preprocessing\Cleaned_data.csv')
data.head(5)

   label                                  text_preprocessed
0  human  talk gene editing ethic sec feel like people c...
1  human  update election integrity concern complicated ...
2     ai  analyst closely watching development related c...
3  human  paper examines genomic research breakthrough c...
4     ai  existing literature student debt crisis predom...

In [39]:
# labelling encoding

encoder = LabelEncoder()
data['label'] = encoder.fit_transform(data['label'])

In [40]:
data['label'].value_counts()

label
1    1334
0     666
Name: count, dtype: int64

In [41]:
#splitting the data
X = data.drop('label',axis=1)
y = data['label']

In [42]:
# shape of the data
print(f'Shape of the feature dataset {X.shape}')
print(f'Shape of the target dataset {y.shape}')

# print the first text in the feature datasets
print(data['text_preprocessed'][0])
X.head()

Shape of the feature dataset (2000, 1)
Shape of the target dataset (2000,)
talk gene editing ethic sec feel like people completely missing point bigger realize

                                   text_preprocessed
0  talk gene editing ethic sec feel like people c...
1  update election integrity concern complicated ...
2  analyst closely watching development related c...
3  paper examines genomic research breakthrough c...
4  existing literature student debt crisis predom...

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print(f'Shape of X_train {X_train.shape}')
print