In [18]:
#importing dependencies
import os 
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import re
from nltk.corpus import stopwords

In [19]:
nltk.download('stopwords')
nltk.download('punktab')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\IKE\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Error loading punktab: Package 'punktab' not found in
[nltk_data]     index

False

In [20]:
data = pd.read_csv(r'C:\Users\IKE\Desktop\Human_VS_AI\eda&preprocessing\AI VS Human.csv')
data.head()

   label                                       text_content
0  human  can we talk about gene editing ethics for a se...
1  human  update on election integrity concerns: it's co...
2     ai  Analysts are closely watching developments rel...
3  human  This paper examines genomic research breakthro...
4     ai  Existing literature on student debt crisis has...

In [21]:
#preprocess the text
def preprocessor(text):
    #convert text to lower case
    text = text.lower()

    # remove special characters
    text = text = re.sub(r'[^a-z\s]', '', text)

    # tokenize text
    token = word_tokenize(text)

    # stopwords
    stop_words = set(stopwords.words('english'))

    tokens = [word for word in token if word not in stop_words and len(word) >1]

    # apply lemmitization
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return ' '.join(tokens)

data['text_preprocessed'] = data['text_content'].apply(preprocessor)
data.head(4)

,label,text_content,text_preprocessed
0,human,can we talk about gene editing ethics for a se...,talk gene editing ethic sec feel like people c...
1,human,update on election integrity concerns: it's co...,update election integrity concern complicated ...
2,ai,Analysts are closely watching developments rel...,analyst closely watching development related c...
3,human,This paper examines genomic research breakthro...,paper examines genomic research breakthrough c...

In [22]:
preprocessed_data = data.copy()

# saving the preprocessed data
preprocessed_data.to_csv('Cleaned_data.csv',index=False)